# REPLICA EL EJERCICIO DE BOLETERIA TOMAS POR FAVOR TE LO PIDO
# SE QUE AHORA ESTAMOS ODIOSOS Y CON SUEÑO PERO POR FAVOR RECUERDA ESTO
# HAZ EL EJERCICIO, ESTAMOS OXIDADOS CON PYTHON TE LO PIDO POR FAVOR
# YA NO SE QUE MAS PONER FALTAN 40 MINUTOS Y YO SOLO PIENSO EN MORIRME
# BUSQUEMOS UN CODIGO ROBUSTO, REPASA DICCIONARIOS, TUPLAS Y COMO LLAMAR A CADA ELEMENTO
# DENTRO DE ESTAS. PODEMOS VOLVER AL NIVEL BASICO QUE TENIAMOS ANTES SIN ANIDAR TANTOS IF
# ====== CONFIO EN QUE EN UN MEJOR ESTADO COGNITIVO LO HARAS BIEN =======
# NO DEPENDAS TANTO DE LA IA PRIMERO ARMA ALGO TU MISMO Y PREGUNTA QUE ESTA FALLANDO


# No lo hiciste, pero si has retomado el ritmo, en algun momento te sentiras seguro de seguir con esto
# Hoy tuviste una revelacion en el uso del while tru y wl try except